* VCL-Modifications
PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/C2A/M_EXT_PAR CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /C2A/M_EXT_PAR-EXTENSION_NAME .
    FIELD /C2A/M_EXT_PAR-PARAMETER_NAME .
    FIELD /C2A/M_EXT_PAR-DB_FIELD .
    FIELD /C2A/M_EXT_PAR-HAS_VALUE_HELP .
    FIELD /C2A/M_EXT_PAR-HAS_HELP .
    FIELD /C2A/M_EXT_PAR-IMPLEMENTING_CLASS .
    FIELD /C2A/M_EXT_PAR-ATTRIBUTE_NAME .
    FIELD /C2A/M_EXT_PAR-PARAMETER_TEXT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    MODULE COMPLETE_/C2A/M_EXT_PAR ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /C2A/M_EXT_PAR-EXTENSION_NAME .
    FIELD /C2A/M_EXT_PAR-PARAMETER_NAME .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
*
PROCESS ON VALUE-REQUEST.
    FIELD  /C2A/M_EXT_PAR-EXTENSION_NAME MODULE VCL_HELP_VALUES.
