PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/C2A/M_EXT_HDR CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /C2A/M_EXT_HDR-EXTENSION_NAME .
    FIELD /C2A/M_EXT_HDR-IMPLEMENTING_CLASS .
    FIELD /C2A/M_EXT_HDR-ALTERNATIVE_SELECTION .
    FIELD /C2A/M_EXT_HDR-SELECTION_TEXT .
    FIELD /C2A/M_EXT_HDR-ALTERNATIVE_DISPLAY .
    FIELD /C2A/M_EXT_HDR-DISPLAY_TEXT .
    FIELD /C2A/M_EXT_HDR-EXTENSION_TEXT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /C2A/M_EXT_HDR-EXTENSION_NAME .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
