CLASS /c2a/cl_version DEFINITION
  PUBLIC ABSTRACT FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.
    CONSTANTS version TYPE string VALUE '2.0.0' ##NO_TEXT.
ENDCLASS.


CLASS /c2a/cl_version IMPLEMENTATION.
ENDCLASS.
