PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/C2A/M_REPORT CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /C2A/M_REPORT-CDS_VIEW .
    FIELD /C2A/M_REPORT-PROGNAME .
    FIELD /C2A/M_REPORT-DYNPRO .
    FIELD /C2A/M_REPORT-AUTHOR .
    FIELD /C2A/M_REPORT-GENERATED_AT .
    FIELD /C2A/M_REPORT-NO_GENERATION .
    FIELD /C2A/M_REPORT-ADD_FUNCTIONS_DISPLAY_MODE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /C2A/M_REPORT-CDS_VIEW .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
