PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/C2A/M_NAV CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /C2A/M_NAV-SEMANTIC_OBJECT .
    FIELD /C2A/M_NAV-SEMANTIC_ACTION .
    FIELD /C2A/M_NAV-FUNCTION .
    FIELD /C2A/M_NAV-DEFAULT_PARAMETER .
    FIELD /C2A/M_NAV-CONVERSION_EXIT .
    FIELD /C2A/M_NAV-OBJECT_TYPE .
    FIELD /C2A/M_NAV-OBJECT_METHOD .
    FIELD /C2A/M_NAV-TRANSACTION_CODE .
    FIELD /C2A/M_NAV-PARAMETER_ID .
    FIELD /C2A/M_NAV-CLASS .
    FIELD /C2A/M_NAV-METHOD .
    FIELD /C2A/M_NAV-METHOD_PARAMETER .
    FIELD /C2A/M_NAV-MASS_PROCESSING .
    FIELD /C2A/M_NAV-REFRESH_AFTER_ACTION .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /C2A/M_NAV-SEMANTIC_OBJECT .
    FIELD /C2A/M_NAV-SEMANTIC_ACTION .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
