*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /C2A/M_EXT_HDR..................................*
FORM GET_DATA_/C2A/M_EXT_HDR.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /C2A/EXT_HDR WHERE
(VIM_WHERETAB) .
    CLEAR /C2A/M_EXT_HDR .
/C2A/M_EXT_HDR-EXTENSION_NAME =
/C2A/EXT_HDR-EXTENSION_NAME .
/C2A/M_EXT_HDR-IMPLEMENTING_CLASS =
/C2A/EXT_HDR-IMPLEMENTING_CLASS .
/C2A/M_EXT_HDR-ALTERNATIVE_SELECTION =
/C2A/EXT_HDR-ALTERNATIVE_SELECTION .
/C2A/M_EXT_HDR-ALTERNATIVE_DISPLAY =
/C2A/EXT_HDR-ALTERNATIVE_DISPLAY .
    SELECT SINGLE * FROM /C2A/EXT_HDRT WHERE
EXTENSION_NAME = /C2A/EXT_HDR-EXTENSION_NAME AND
LANGUAGE = SY-LANGU .
    IF SY-SUBRC EQ 0.
/C2A/M_EXT_HDR-SELECTION_TEXT =
/C2A/EXT_HDRT-SELECTION_TEXT .
/C2A/M_EXT_HDR-DISPLAY_TEXT =
/C2A/EXT_HDRT-DISPLAY_TEXT .
/C2A/M_EXT_HDR-EXTENSION_TEXT =
/C2A/EXT_HDRT-EXTENSION_TEXT .
    ENDIF.
<VIM_TOTAL_STRUC> = /C2A/M_EXT_HDR.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/C2A/M_EXT_HDR .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /C2A/M_EXT_HDR.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/C2A/M_EXT_HDR-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /C2A/EXT_HDR WHERE
  EXTENSION_NAME = /C2A/M_EXT_HDR-EXTENSION_NAME .
    IF SY-SUBRC = 0.
    DELETE /C2A/EXT_HDR .
    ENDIF.
    DELETE FROM /C2A/EXT_HDRT WHERE
    EXTENSION_NAME = /C2A/EXT_HDR-EXTENSION_NAME .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /C2A/EXT_HDR WHERE
  EXTENSION_NAME = /C2A/M_EXT_HDR-EXTENSION_NAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /C2A/EXT_HDR.
    ENDIF.
/C2A/EXT_HDR-EXTENSION_NAME =
/C2A/M_EXT_HDR-EXTENSION_NAME .
/C2A/EXT_HDR-IMPLEMENTING_CLASS =
/C2A/M_EXT_HDR-IMPLEMENTING_CLASS .
/C2A/EXT_HDR-ALTERNATIVE_SELECTION =
/C2A/M_EXT_HDR-ALTERNATIVE_SELECTION .
/C2A/EXT_HDR-ALTERNATIVE_DISPLAY =
/C2A/M_EXT_HDR-ALTERNATIVE_DISPLAY .
    IF SY-SUBRC = 0.
    UPDATE /C2A/EXT_HDR ##WARN_OK.
    ELSE.
    INSERT /C2A/EXT_HDR .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM /C2A/EXT_HDRT WHERE
    EXTENSION_NAME = /C2A/EXT_HDR-EXTENSION_NAME AND
    LANGUAGE = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR /C2A/EXT_HDRT.
/C2A/EXT_HDRT-EXTENSION_NAME =
/C2A/EXT_HDR-EXTENSION_NAME .
/C2A/EXT_HDRT-LANGUAGE =
SY-LANGU .
      ENDIF.
/C2A/EXT_HDRT-SELECTION_TEXT =
/C2A/M_EXT_HDR-SELECTION_TEXT .
/C2A/EXT_HDRT-DISPLAY_TEXT =
/C2A/M_EXT_HDR-DISPLAY_TEXT .
/C2A/EXT_HDRT-EXTENSION_TEXT =
/C2A/M_EXT_HDR-EXTENSION_TEXT .
    IF SY-SUBRC = 0.
    UPDATE /C2A/EXT_HDRT ##WARN_OK.
    ELSE.
    INSERT /C2A/EXT_HDRT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/C2A/M_EXT_HDR-UPD_FLAG,
STATUS_/C2A/M_EXT_HDR-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/C2A/M_EXT_HDR.
  SELECT SINGLE * FROM /C2A/EXT_HDR WHERE
EXTENSION_NAME = /C2A/M_EXT_HDR-EXTENSION_NAME .
/C2A/M_EXT_HDR-EXTENSION_NAME =
/C2A/EXT_HDR-EXTENSION_NAME .
/C2A/M_EXT_HDR-IMPLEMENTING_CLASS =
/C2A/EXT_HDR-IMPLEMENTING_CLASS .
/C2A/M_EXT_HDR-ALTERNATIVE_SELECTION =
/C2A/EXT_HDR-ALTERNATIVE_SELECTION .
/C2A/M_EXT_HDR-ALTERNATIVE_DISPLAY =
/C2A/EXT_HDR-ALTERNATIVE_DISPLAY .
    SELECT SINGLE * FROM /C2A/EXT_HDRT WHERE
EXTENSION_NAME = /C2A/EXT_HDR-EXTENSION_NAME AND
LANGUAGE = SY-LANGU .
    IF SY-SUBRC EQ 0.
/C2A/M_EXT_HDR-SELECTION_TEXT =
/C2A/EXT_HDRT-SELECTION_TEXT .
/C2A/M_EXT_HDR-DISPLAY_TEXT =
/C2A/EXT_HDRT-DISPLAY_TEXT .
/C2A/M_EXT_HDR-EXTENSION_TEXT =
/C2A/EXT_HDRT-EXTENSION_TEXT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /C2A/M_EXT_HDR-SELECTION_TEXT .
      CLEAR /C2A/M_EXT_HDR-DISPLAY_TEXT .
      CLEAR /C2A/M_EXT_HDR-EXTENSION_TEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/C2A/M_EXT_HDR USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /C2A/M_EXT_HDR-EXTENSION_NAME TO
/C2A/EXT_HDR-EXTENSION_NAME .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/C2A/EXT_HDR'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /C2A/EXT_HDR TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/C2A/EXT_HDR'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE /C2A/EXT_HDR-EXTENSION_NAME TO
/C2A/EXT_HDRT-EXTENSION_NAME .
MOVE SY-LANGU TO
/C2A/EXT_HDRT-LANGUAGE .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/C2A/EXT_HDRT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /C2A/EXT_HDRT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/C2A/EXT_HDRT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /C2A/M_EXT_PAR..................................*
FORM GET_DATA_/C2A/M_EXT_PAR.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /C2A/EXT_PAR WHERE
(VIM_WHERETAB) .
    CLEAR /C2A/M_EXT_PAR .
/C2A/M_EXT_PAR-EXTENSION_NAME =
/C2A/EXT_PAR-EXTENSION_NAME .
/C2A/M_EXT_PAR-PARAMETER_NAME =
/C2A/EXT_PAR-PARAMETER_NAME .
/C2A/M_EXT_PAR-DB_FIELD =
/C2A/EXT_PAR-DB_FIELD .
/C2A/M_EXT_PAR-HAS_VALUE_HELP =
/C2A/EXT_PAR-HAS_VALUE_HELP .
/C2A/M_EXT_PAR-HAS_HELP =
/C2A/EXT_PAR-HAS_HELP .
/C2A/M_EXT_PAR-ATTRIBUTE_NAME =
/C2A/EXT_PAR-ATTRIBUTE_NAME .
    SELECT SINGLE * FROM /C2A/EXT_PART WHERE
EXTENSION_NAME = /C2A/EXT_PAR-EXTENSION_NAME AND
PARAMETER_NAME = /C2A/EXT_PAR-PARAMETER_NAME AND
LANGUAGE = SY-LANGU .
    IF SY-SUBRC EQ 0.
/C2A/M_EXT_PAR-PARAMETER_TEXT =
/C2A/EXT_PART-PARAMETER_TEXT .
    ENDIF.
    SELECT SINGLE * FROM /C2A/EXT_HDR WHERE
EXTENSION_NAME = /C2A/EXT_PAR-EXTENSION_NAME .
    IF SY-SUBRC EQ 0.
/C2A/M_EXT_PAR-IMPLEMENTING_CLASS =
/C2A/EXT_HDR-IMPLEMENTING_CLASS .
    ENDIF.
<VIM_TOTAL_STRUC> = /C2A/M_EXT_PAR.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/C2A/M_EXT_PAR .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /C2A/M_EXT_PAR.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/C2A/M_EXT_PAR-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /C2A/EXT_PAR WHERE
  EXTENSION_NAME = /C2A/M_EXT_PAR-EXTENSION_NAME AND
  PARAMETER_NAME = /C2A/M_EXT_PAR-PARAMETER_NAME .
    IF SY-SUBRC = 0.
    DELETE /C2A/EXT_PAR .
    ENDIF.
    DELETE FROM /C2A/EXT_PART WHERE
    EXTENSION_NAME = /C2A/EXT_PAR-EXTENSION_NAME AND
    PARAMETER_NAME = /C2A/EXT_PAR-PARAMETER_NAME .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /C2A/EXT_PAR WHERE
  EXTENSION_NAME = /C2A/M_EXT_PAR-EXTENSION_NAME AND
  PARAMETER_NAME = /C2A/M_EXT_PAR-PARAMETER_NAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /C2A/EXT_PAR.
    ENDIF.
/C2A/EXT_PAR-EXTENSION_NAME =
/C2A/M_EXT_PAR-EXTENSION_NAME .
/C2A/EXT_PAR-PARAMETER_NAME =
/C2A/M_EXT_PAR-PARAMETER_NAME .
/C2A/EXT_PAR-DB_FIELD =
/C2A/M_EXT_PAR-DB_FIELD .
/C2A/EXT_PAR-HAS_VALUE_HELP =
/C2A/M_EXT_PAR-HAS_VALUE_HELP .
/C2A/EXT_PAR-HAS_HELP =
/C2A/M_EXT_PAR-HAS_HELP .
/C2A/EXT_PAR-ATTRIBUTE_NAME =
/C2A/M_EXT_PAR-ATTRIBUTE_NAME .
    IF SY-SUBRC = 0.
    UPDATE /C2A/EXT_PAR ##WARN_OK.
    ELSE.
    INSERT /C2A/EXT_PAR .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM /C2A/EXT_PART WHERE
    EXTENSION_NAME = /C2A/EXT_PAR-EXTENSION_NAME AND
    PARAMETER_NAME = /C2A/EXT_PAR-PARAMETER_NAME AND
    LANGUAGE = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR /C2A/EXT_PART.
/C2A/EXT_PART-EXTENSION_NAME =
/C2A/EXT_PAR-EXTENSION_NAME .
/C2A/EXT_PART-PARAMETER_NAME =
/C2A/EXT_PAR-PARAMETER_NAME .
/C2A/EXT_PART-LANGUAGE =
SY-LANGU .
      ENDIF.
/C2A/EXT_PART-PARAMETER_TEXT =
/C2A/M_EXT_PAR-PARAMETER_TEXT .
    IF SY-SUBRC = 0.
    UPDATE /C2A/EXT_PART ##WARN_OK.
    ELSE.
    INSERT /C2A/EXT_PART .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/C2A/M_EXT_PAR-UPD_FLAG,
STATUS_/C2A/M_EXT_PAR-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/C2A/M_EXT_PAR.
  SELECT SINGLE * FROM /C2A/EXT_PAR WHERE
EXTENSION_NAME = /C2A/M_EXT_PAR-EXTENSION_NAME AND
PARAMETER_NAME = /C2A/M_EXT_PAR-PARAMETER_NAME .
/C2A/M_EXT_PAR-EXTENSION_NAME =
/C2A/EXT_PAR-EXTENSION_NAME .
/C2A/M_EXT_PAR-PARAMETER_NAME =
/C2A/EXT_PAR-PARAMETER_NAME .
/C2A/M_EXT_PAR-DB_FIELD =
/C2A/EXT_PAR-DB_FIELD .
/C2A/M_EXT_PAR-HAS_VALUE_HELP =
/C2A/EXT_PAR-HAS_VALUE_HELP .
/C2A/M_EXT_PAR-HAS_HELP =
/C2A/EXT_PAR-HAS_HELP .
/C2A/M_EXT_PAR-ATTRIBUTE_NAME =
/C2A/EXT_PAR-ATTRIBUTE_NAME .
    SELECT SINGLE * FROM /C2A/EXT_PART WHERE
EXTENSION_NAME = /C2A/EXT_PAR-EXTENSION_NAME AND
PARAMETER_NAME = /C2A/EXT_PAR-PARAMETER_NAME AND
LANGUAGE = SY-LANGU .
    IF SY-SUBRC EQ 0.
/C2A/M_EXT_PAR-PARAMETER_TEXT =
/C2A/EXT_PART-PARAMETER_TEXT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /C2A/M_EXT_PAR-PARAMETER_TEXT .
    ENDIF.
    SELECT SINGLE * FROM /C2A/EXT_HDR WHERE
EXTENSION_NAME = /C2A/EXT_PAR-EXTENSION_NAME .
    IF SY-SUBRC EQ 0.
/C2A/M_EXT_PAR-IMPLEMENTING_CLASS =
/C2A/EXT_HDR-IMPLEMENTING_CLASS .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /C2A/M_EXT_PAR-IMPLEMENTING_CLASS .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/C2A/M_EXT_PAR USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /C2A/M_EXT_PAR-EXTENSION_NAME TO
/C2A/EXT_PAR-EXTENSION_NAME .
MOVE /C2A/M_EXT_PAR-PARAMETER_NAME TO
/C2A/EXT_PAR-PARAMETER_NAME .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/C2A/EXT_PAR'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /C2A/EXT_PAR TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/C2A/EXT_PAR'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE /C2A/EXT_PAR-EXTENSION_NAME TO
/C2A/EXT_PART-EXTENSION_NAME .
MOVE /C2A/EXT_PAR-PARAMETER_NAME TO
/C2A/EXT_PART-PARAMETER_NAME .
MOVE SY-LANGU TO
/C2A/EXT_PART-LANGUAGE .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/C2A/EXT_PART'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /C2A/EXT_PART TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/C2A/EXT_PART'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/C2A/M_EXT_PAR USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/C2A/EXT_PAR-EXTENSION_NAME =
/C2A/M_EXT_PAR-EXTENSION_NAME .
/C2A/EXT_PAR-PARAMETER_NAME =
/C2A/M_EXT_PAR-PARAMETER_NAME .
/C2A/EXT_PAR-DB_FIELD =
/C2A/M_EXT_PAR-DB_FIELD .
/C2A/EXT_PAR-HAS_VALUE_HELP =
/C2A/M_EXT_PAR-HAS_VALUE_HELP .
/C2A/EXT_PAR-HAS_HELP =
/C2A/M_EXT_PAR-HAS_HELP .
/C2A/EXT_PAR-ATTRIBUTE_NAME =
/C2A/M_EXT_PAR-ATTRIBUTE_NAME .
  /C2A/EXT_PART-EXTENSION_NAME =
    /C2A/EXT_PAR-EXTENSION_NAME .
  /C2A/EXT_PART-PARAMETER_NAME =
    /C2A/EXT_PAR-PARAMETER_NAME .
  /C2A/EXT_PART-LANGUAGE =
    SY-LANGU .
/C2A/EXT_PART-PARAMETER_TEXT =
/C2A/M_EXT_PAR-PARAMETER_TEXT .
    SELECT SINGLE * FROM /C2A/EXT_HDR WHERE
EXTENSION_NAME = /C2A/EXT_PAR-EXTENSION_NAME .
    IF SY-SUBRC EQ 0.
/C2A/M_EXT_PAR-IMPLEMENTING_CLASS =
/C2A/EXT_HDR-IMPLEMENTING_CLASS .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /C2A/M_EXT_PAR-IMPLEMENTING_CLASS .
    ENDIF.
ENDFORM.
*...processing: /C2A/M_IOC_CLIF.................................*
FORM GET_DATA_/C2A/M_IOC_CLIF.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /C2A/IOC_CLIF WHERE
(VIM_WHERETAB) .
    CLEAR /C2A/M_IOC_CLIF .
/C2A/M_IOC_CLIF-INTERFACE =
/C2A/IOC_CLIF-INTERFACE .
/C2A/M_IOC_CLIF-CLASS =
/C2A/IOC_CLIF-CLASS .
<VIM_TOTAL_STRUC> = /C2A/M_IOC_CLIF.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/C2A/M_IOC_CLIF .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /C2A/M_IOC_CLIF.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/C2A/M_IOC_CLIF-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /C2A/IOC_CLIF WHERE
  INTERFACE = /C2A/M_IOC_CLIF-INTERFACE .
    IF SY-SUBRC = 0.
    DELETE /C2A/IOC_CLIF .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /C2A/IOC_CLIF WHERE
  INTERFACE = /C2A/M_IOC_CLIF-INTERFACE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /C2A/IOC_CLIF.
    ENDIF.
/C2A/IOC_CLIF-INTERFACE =
/C2A/M_IOC_CLIF-INTERFACE .
/C2A/IOC_CLIF-CLASS =
/C2A/M_IOC_CLIF-CLASS .
    IF SY-SUBRC = 0.
    UPDATE /C2A/IOC_CLIF ##WARN_OK.
    ELSE.
    INSERT /C2A/IOC_CLIF .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/C2A/M_IOC_CLIF-UPD_FLAG,
STATUS_/C2A/M_IOC_CLIF-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/C2A/M_IOC_CLIF.
  SELECT SINGLE * FROM /C2A/IOC_CLIF WHERE
INTERFACE = /C2A/M_IOC_CLIF-INTERFACE .
/C2A/M_IOC_CLIF-INTERFACE =
/C2A/IOC_CLIF-INTERFACE .
/C2A/M_IOC_CLIF-CLASS =
/C2A/IOC_CLIF-CLASS .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/C2A/M_IOC_CLIF USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /C2A/M_IOC_CLIF-INTERFACE TO
/C2A/IOC_CLIF-INTERFACE .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/C2A/IOC_CLIF'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /C2A/IOC_CLIF TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/C2A/IOC_CLIF'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /C2A/M_NAV......................................*
FORM GET_DATA_/C2A/M_NAV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /C2A/NAVIGATION WHERE
(VIM_WHERETAB) .
    CLEAR /C2A/M_NAV .
/C2A/M_NAV-SEMANTIC_OBJECT =
/C2A/NAVIGATION-SEMANTIC_OBJECT .
/C2A/M_NAV-SEMANTIC_ACTION =
/C2A/NAVIGATION-SEMANTIC_ACTION .
/C2A/M_NAV-FUNCTION =
/C2A/NAVIGATION-FUNCTION .
/C2A/M_NAV-DEFAULT_PARAMETER =
/C2A/NAVIGATION-DEFAULT_PARAMETER .
/C2A/M_NAV-CONVERSION_EXIT =
/C2A/NAVIGATION-CONVERSION_EXIT .
/C2A/M_NAV-OBJECT_TYPE =
/C2A/NAVIGATION-OBJECT_TYPE .
/C2A/M_NAV-OBJECT_METHOD =
/C2A/NAVIGATION-OBJECT_METHOD .
/C2A/M_NAV-TRANSACTION_CODE =
/C2A/NAVIGATION-TRANSACTION_CODE .
/C2A/M_NAV-PARAMETER_ID =
/C2A/NAVIGATION-PARAMETER_ID .
/C2A/M_NAV-CLASS =
/C2A/NAVIGATION-CLASS .
/C2A/M_NAV-METHOD =
/C2A/NAVIGATION-METHOD .
/C2A/M_NAV-METHOD_PARAMETER =
/C2A/NAVIGATION-METHOD_PARAMETER .
/C2A/M_NAV-MASS_PROCESSING =
/C2A/NAVIGATION-MASS_PROCESSING .
/C2A/M_NAV-REFRESH_AFTER_ACTION =
/C2A/NAVIGATION-REFRESH_AFTER_ACTION .
<VIM_TOTAL_STRUC> = /C2A/M_NAV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/C2A/M_NAV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /C2A/M_NAV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/C2A/M_NAV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /C2A/NAVIGATION WHERE
  SEMANTIC_OBJECT = /C2A/M_NAV-SEMANTIC_OBJECT AND
  SEMANTIC_ACTION = /C2A/M_NAV-SEMANTIC_ACTION .
    IF SY-SUBRC = 0.
    DELETE /C2A/NAVIGATION .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /C2A/NAVIGATION WHERE
  SEMANTIC_OBJECT = /C2A/M_NAV-SEMANTIC_OBJECT AND
  SEMANTIC_ACTION = /C2A/M_NAV-SEMANTIC_ACTION .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /C2A/NAVIGATION.
    ENDIF.
/C2A/NAVIGATION-SEMANTIC_OBJECT =
/C2A/M_NAV-SEMANTIC_OBJECT .
/C2A/NAVIGATION-SEMANTIC_ACTION =
/C2A/M_NAV-SEMANTIC_ACTION .
/C2A/NAVIGATION-FUNCTION =
/C2A/M_NAV-FUNCTION .
/C2A/NAVIGATION-DEFAULT_PARAMETER =
/C2A/M_NAV-DEFAULT_PARAMETER .
/C2A/NAVIGATION-CONVERSION_EXIT =
/C2A/M_NAV-CONVERSION_EXIT .
/C2A/NAVIGATION-OBJECT_TYPE =
/C2A/M_NAV-OBJECT_TYPE .
/C2A/NAVIGATION-OBJECT_METHOD =
/C2A/M_NAV-OBJECT_METHOD .
/C2A/NAVIGATION-TRANSACTION_CODE =
/C2A/M_NAV-TRANSACTION_CODE .
/C2A/NAVIGATION-PARAMETER_ID =
/C2A/M_NAV-PARAMETER_ID .
/C2A/NAVIGATION-CLASS =
/C2A/M_NAV-CLASS .
/C2A/NAVIGATION-METHOD =
/C2A/M_NAV-METHOD .
/C2A/NAVIGATION-METHOD_PARAMETER =
/C2A/M_NAV-METHOD_PARAMETER .
/C2A/NAVIGATION-MASS_PROCESSING =
/C2A/M_NAV-MASS_PROCESSING .
/C2A/NAVIGATION-REFRESH_AFTER_ACTION =
/C2A/M_NAV-REFRESH_AFTER_ACTION .
    IF SY-SUBRC = 0.
    UPDATE /C2A/NAVIGATION ##WARN_OK.
    ELSE.
    INSERT /C2A/NAVIGATION .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/C2A/M_NAV-UPD_FLAG,
STATUS_/C2A/M_NAV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_/C2A/M_NAV.
  SELECT SINGLE * FROM /C2A/NAVIGATION WHERE
SEMANTIC_OBJECT = /C2A/M_NAV-SEMANTIC_OBJECT AND
SEMANTIC_ACTION = /C2A/M_NAV-SEMANTIC_ACTION .
/C2A/M_NAV-SEMANTIC_OBJECT =
/C2A/NAVIGATION-SEMANTIC_OBJECT .
/C2A/M_NAV-SEMANTIC_ACTION =
/C2A/NAVIGATION-SEMANTIC_ACTION .
/C2A/M_NAV-FUNCTION =
/C2A/NAVIGATION-FUNCTION .
/C2A/M_NAV-DEFAULT_PARAMETER =
/C2A/NAVIGATION-DEFAULT_PARAMETER .
/C2A/M_NAV-CONVERSION_EXIT =
/C2A/NAVIGATION-CONVERSION_EXIT .
/C2A/M_NAV-OBJECT_TYPE =
/C2A/NAVIGATION-OBJECT_TYPE .
/C2A/M_NAV-OBJECT_METHOD =
/C2A/NAVIGATION-OBJECT_METHOD .
/C2A/M_NAV-TRANSACTION_CODE =
/C2A/NAVIGATION-TRANSACTION_CODE .
/C2A/M_NAV-PARAMETER_ID =
/C2A/NAVIGATION-PARAMETER_ID .
/C2A/M_NAV-CLASS =
/C2A/NAVIGATION-CLASS .
/C2A/M_NAV-METHOD =
/C2A/NAVIGATION-METHOD .
/C2A/M_NAV-METHOD_PARAMETER =
/C2A/NAVIGATION-METHOD_PARAMETER .
/C2A/M_NAV-MASS_PROCESSING =
/C2A/NAVIGATION-MASS_PROCESSING .
/C2A/M_NAV-REFRESH_AFTER_ACTION =
/C2A/NAVIGATION-REFRESH_AFTER_ACTION .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/C2A/M_NAV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /C2A/M_NAV-SEMANTIC_OBJECT TO
/C2A/NAVIGATION-SEMANTIC_OBJECT .
MOVE /C2A/M_NAV-SEMANTIC_ACTION TO
/C2A/NAVIGATION-SEMANTIC_ACTION .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/C2A/NAVIGATION'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /C2A/NAVIGATION TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/C2A/NAVIGATION'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /C2A/M_NAV_EXIT.................................*
FORM GET_DATA_/C2A/M_NAV_EXIT.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /C2A/NAV_EXIT WHERE
(VIM_WHERETAB) .
    CLEAR /C2A/M_NAV_EXIT .
/C2A/M_NAV_EXIT-SEMANTIC_OBJECT =
/C2A/NAV_EXIT-SEMANTIC_OBJECT .
/C2A/M_NAV_EXIT-SEMANTIC_ACTION =
/C2A/NAV_EXIT-SEMANTIC_ACTION .
/C2A/M_NAV_EXIT-CDS_VIEW =
/C2A/NAV_EXIT-CDS_VIEW .
/C2A/M_NAV_EXIT-IMPLEMENTING_CLASS =
/C2A/NAV_EXIT-IMPLEMENTING_CLASS .
<VIM_TOTAL_STRUC> = /C2A/M_NAV_EXIT.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/C2A/M_NAV_EXIT .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /C2A/M_NAV_EXIT.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/C2A/M_NAV_EXIT-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /C2A/NAV_EXIT WHERE
  SEMANTIC_OBJECT = /C2A/M_NAV_EXIT-SEMANTIC_OBJECT AND
  SEMANTIC_ACTION = /C2A/M_NAV_EXIT-SEMANTIC_ACTION AND
  CDS_VIEW = /C2A/M_NAV_EXIT-CDS_VIEW .
    IF SY-SUBRC = 0.
    DELETE /C2A/NAV_EXIT .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /C2A/NAV_EXIT WHERE
  SEMANTIC_OBJECT = /C2A/M_NAV_EXIT-SEMANTIC_OBJECT AND
  SEMANTIC_ACTION = /C2A/M_NAV_EXIT-SEMANTIC_ACTION AND
  CDS_VIEW = /C2A/M_NAV_EXIT-CDS_VIEW .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /C2A/NAV_EXIT.
    ENDIF.
/C2A/NAV_EXIT-SEMANTIC_OBJECT =
/C2A/M_NAV_EXIT-SEMANTIC_OBJECT .
/C2A/NAV_EXIT-SEMANTIC_ACTION =
/C2A/M_NAV_EXIT-SEMANTIC_ACTION .
/C2A/NAV_EXIT-CDS_VIEW =
/C2A/M_NAV_EXIT-CDS_VIEW .
/C2A/NAV_EXIT-IMPLEMENTING_CLASS =
/C2A/M_NAV_EXIT-IMPLEMENTING_CLASS .
    IF SY-SUBRC = 0.
    UPDATE /C2A/NAV_EXIT ##WARN_OK.
    ELSE.
    INSERT /C2A/NAV_EXIT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/C2A/M_NAV_EXIT-UPD_FLAG,
STATUS_/C2A/M_NAV_EXIT-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/C2A/M_NAV_EXIT.
  SELECT SINGLE * FROM /C2A/NAV_EXIT WHERE
SEMANTIC_OBJECT = /C2A/M_NAV_EXIT-SEMANTIC_OBJECT AND
SEMANTIC_ACTION = /C2A/M_NAV_EXIT-SEMANTIC_ACTION AND
CDS_VIEW = /C2A/M_NAV_EXIT-CDS_VIEW .
/C2A/M_NAV_EXIT-SEMANTIC_OBJECT =
/C2A/NAV_EXIT-SEMANTIC_OBJECT .
/C2A/M_NAV_EXIT-SEMANTIC_ACTION =
/C2A/NAV_EXIT-SEMANTIC_ACTION .
/C2A/M_NAV_EXIT-CDS_VIEW =
/C2A/NAV_EXIT-CDS_VIEW .
/C2A/M_NAV_EXIT-IMPLEMENTING_CLASS =
/C2A/NAV_EXIT-IMPLEMENTING_CLASS .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/C2A/M_NAV_EXIT USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /C2A/M_NAV_EXIT-SEMANTIC_OBJECT TO
/C2A/NAV_EXIT-SEMANTIC_OBJECT .
MOVE /C2A/M_NAV_EXIT-SEMANTIC_ACTION TO
/C2A/NAV_EXIT-SEMANTIC_ACTION .
MOVE /C2A/M_NAV_EXIT-CDS_VIEW TO
/C2A/NAV_EXIT-CDS_VIEW .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/C2A/NAV_EXIT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /C2A/NAV_EXIT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/C2A/NAV_EXIT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /C2A/M_REPORT...................................*
FORM GET_DATA_/C2A/M_REPORT.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /C2A/REPORT WHERE
(VIM_WHERETAB) .
    CLEAR /C2A/M_REPORT .
/C2A/M_REPORT-CDS_VIEW =
/C2A/REPORT-CDS_VIEW .
/C2A/M_REPORT-PROGNAME =
/C2A/REPORT-PROGNAME .
/C2A/M_REPORT-DYNPRO =
/C2A/REPORT-DYNPRO .
/C2A/M_REPORT-AUTHOR =
/C2A/REPORT-AUTHOR .
/C2A/M_REPORT-GENERATED_AT =
/C2A/REPORT-GENERATED_AT .
/C2A/M_REPORT-NO_GENERATION =
/C2A/REPORT-NO_GENERATION .
/C2A/M_REPORT-ADD_FUNCTIONS_DISPLAY_MODE =
/C2A/REPORT-ADD_FUNCTIONS_DISPLAY_MODE .
<VIM_TOTAL_STRUC> = /C2A/M_REPORT.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/C2A/M_REPORT .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /C2A/M_REPORT.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/C2A/M_REPORT-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /C2A/REPORT WHERE
  CDS_VIEW = /C2A/M_REPORT-CDS_VIEW .
    IF SY-SUBRC = 0.
    DELETE /C2A/REPORT .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /C2A/REPORT WHERE
  CDS_VIEW = /C2A/M_REPORT-CDS_VIEW .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /C2A/REPORT.
    ENDIF.
/C2A/REPORT-CDS_VIEW =
/C2A/M_REPORT-CDS_VIEW .
/C2A/REPORT-PROGNAME =
/C2A/M_REPORT-PROGNAME .
/C2A/REPORT-DYNPRO =
/C2A/M_REPORT-DYNPRO .
/C2A/REPORT-AUTHOR =
/C2A/M_REPORT-AUTHOR .
/C2A/REPORT-GENERATED_AT =
/C2A/M_REPORT-GENERATED_AT .
/C2A/REPORT-NO_GENERATION =
/C2A/M_REPORT-NO_GENERATION .
/C2A/REPORT-ADD_FUNCTIONS_DISPLAY_MODE =
/C2A/M_REPORT-ADD_FUNCTIONS_DISPLAY_MODE .
    IF SY-SUBRC = 0.
    UPDATE /C2A/REPORT ##WARN_OK.
    ELSE.
    INSERT /C2A/REPORT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/C2A/M_REPORT-UPD_FLAG,
STATUS_/C2A/M_REPORT-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/C2A/M_REPORT.
  SELECT SINGLE * FROM /C2A/REPORT WHERE
CDS_VIEW = /C2A/M_REPORT-CDS_VIEW .
/C2A/M_REPORT-CDS_VIEW =
/C2A/REPORT-CDS_VIEW .
/C2A/M_REPORT-PROGNAME =
/C2A/REPORT-PROGNAME .
/C2A/M_REPORT-DYNPRO =
/C2A/REPORT-DYNPRO .
/C2A/M_REPORT-AUTHOR =
/C2A/REPORT-AUTHOR .
/C2A/M_REPORT-GENERATED_AT =
/C2A/REPORT-GENERATED_AT .
/C2A/M_REPORT-NO_GENERATION =
/C2A/REPORT-NO_GENERATION .
/C2A/M_REPORT-ADD_FUNCTIONS_DISPLAY_MODE =
/C2A/REPORT-ADD_FUNCTIONS_DISPLAY_MODE .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/C2A/M_REPORT USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /C2A/M_REPORT-CDS_VIEW TO
/C2A/REPORT-CDS_VIEW .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/C2A/REPORT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /C2A/REPORT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/C2A/REPORT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /C2A/M_REP_EXT..................................*
FORM GET_DATA_/C2A/M_REP_EXT.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /C2A/REP_EXT WHERE
(VIM_WHERETAB) .
    CLEAR /C2A/M_REP_EXT .
/C2A/M_REP_EXT-CDS_VIEW =
/C2A/REP_EXT-CDS_VIEW .
/C2A/M_REP_EXT-EXTENSION_NAME =
/C2A/REP_EXT-EXTENSION_NAME .
/C2A/M_REP_EXT-ACTIVE =
/C2A/REP_EXT-ACTIVE .
/C2A/M_REP_EXT-ACTIVATED_ON =
/C2A/REP_EXT-ACTIVATED_ON .
<VIM_TOTAL_STRUC> = /C2A/M_REP_EXT.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/C2A/M_REP_EXT .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /C2A/M_REP_EXT.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/C2A/M_REP_EXT-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /C2A/REP_EXT WHERE
  CDS_VIEW = /C2A/M_REP_EXT-CDS_VIEW AND
  EXTENSION_NAME = /C2A/M_REP_EXT-EXTENSION_NAME .
    IF SY-SUBRC = 0.
    DELETE /C2A/REP_EXT .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /C2A/REP_EXT WHERE
  CDS_VIEW = /C2A/M_REP_EXT-CDS_VIEW AND
  EXTENSION_NAME = /C2A/M_REP_EXT-EXTENSION_NAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /C2A/REP_EXT.
    ENDIF.
/C2A/REP_EXT-CDS_VIEW =
/C2A/M_REP_EXT-CDS_VIEW .
/C2A/REP_EXT-EXTENSION_NAME =
/C2A/M_REP_EXT-EXTENSION_NAME .
/C2A/REP_EXT-ACTIVE =
/C2A/M_REP_EXT-ACTIVE .
/C2A/REP_EXT-ACTIVATED_ON =
/C2A/M_REP_EXT-ACTIVATED_ON .
    IF SY-SUBRC = 0.
    UPDATE /C2A/REP_EXT ##WARN_OK.
    ELSE.
    INSERT /C2A/REP_EXT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/C2A/M_REP_EXT-UPD_FLAG,
STATUS_/C2A/M_REP_EXT-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/C2A/M_REP_EXT.
  SELECT SINGLE * FROM /C2A/REP_EXT WHERE
CDS_VIEW = /C2A/M_REP_EXT-CDS_VIEW AND
EXTENSION_NAME = /C2A/M_REP_EXT-EXTENSION_NAME .
/C2A/M_REP_EXT-CDS_VIEW =
/C2A/REP_EXT-CDS_VIEW .
/C2A/M_REP_EXT-EXTENSION_NAME =
/C2A/REP_EXT-EXTENSION_NAME .
/C2A/M_REP_EXT-ACTIVE =
/C2A/REP_EXT-ACTIVE .
/C2A/M_REP_EXT-ACTIVATED_ON =
/C2A/REP_EXT-ACTIVATED_ON .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/C2A/M_REP_EXT USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /C2A/M_REP_EXT-CDS_VIEW TO
/C2A/REP_EXT-CDS_VIEW .
MOVE /C2A/M_REP_EXT-EXTENSION_NAME TO
/C2A/REP_EXT-EXTENSION_NAME .
ENDFORM.
*---------------------------------------------------------------------*
*...processing: /C2A/M_REP_PARAM................................*
FORM GET_DATA_/C2A/M_REP_PARAM.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /C2A/REP_PARAMS WHERE
(VIM_WHERETAB) .
    CLEAR /C2A/M_REP_PARAM .
/C2A/M_REP_PARAM-PROGNAME =
/C2A/REP_PARAMS-PROGNAME .
/C2A/M_REP_PARAM-SEL_NAME =
/C2A/REP_PARAMS-SEL_NAME .
/C2A/M_REP_PARAM-CDS_VIEW =
/C2A/REP_PARAMS-CDS_VIEW .
/C2A/M_REP_PARAM-PARNAME =
/C2A/REP_PARAMS-PARNAME .
<VIM_TOTAL_STRUC> = /C2A/M_REP_PARAM.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/C2A/M_REP_PARAM .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /C2A/M_REP_PARAM.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/C2A/M_REP_PARAM-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /C2A/REP_PARAMS WHERE
  PROGNAME = /C2A/M_REP_PARAM-PROGNAME AND
  SEL_NAME = /C2A/M_REP_PARAM-SEL_NAME .
    IF SY-SUBRC = 0.
    DELETE /C2A/REP_PARAMS .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /C2A/REP_PARAMS WHERE
  PROGNAME = /C2A/M_REP_PARAM-PROGNAME AND
  SEL_NAME = /C2A/M_REP_PARAM-SEL_NAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /C2A/REP_PARAMS.
    ENDIF.
/C2A/REP_PARAMS-PROGNAME =
/C2A/M_REP_PARAM-PROGNAME .
/C2A/REP_PARAMS-SEL_NAME =
/C2A/M_REP_PARAM-SEL_NAME .
/C2A/REP_PARAMS-CDS_VIEW =
/C2A/M_REP_PARAM-CDS_VIEW .
/C2A/REP_PARAMS-PARNAME =
/C2A/M_REP_PARAM-PARNAME .
    IF SY-SUBRC = 0.
    UPDATE /C2A/REP_PARAMS ##WARN_OK.
    ELSE.
    INSERT /C2A/REP_PARAMS .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/C2A/M_REP_PARAM-UPD_FLAG,
STATUS_/C2A/M_REP_PARAM-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/C2A/M_REP_PARAM.
  SELECT SINGLE * FROM /C2A/REP_PARAMS WHERE
PROGNAME = /C2A/M_REP_PARAM-PROGNAME AND
SEL_NAME = /C2A/M_REP_PARAM-SEL_NAME .
/C2A/M_REP_PARAM-PROGNAME =
/C2A/REP_PARAMS-PROGNAME .
/C2A/M_REP_PARAM-SEL_NAME =
/C2A/REP_PARAMS-SEL_NAME .
/C2A/M_REP_PARAM-CDS_VIEW =
/C2A/REP_PARAMS-CDS_VIEW .
/C2A/M_REP_PARAM-PARNAME =
/C2A/REP_PARAMS-PARNAME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/C2A/M_REP_PARAM USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /C2A/M_REP_PARAM-PROGNAME TO
/C2A/REP_PARAMS-PROGNAME .
MOVE /C2A/M_REP_PARAM-SEL_NAME TO
/C2A/REP_PARAMS-SEL_NAME .
ENDFORM.
*---------------------------------------------------------------------*
*...processing: /C2A/M_REP_SELOP................................*
FORM GET_DATA_/C2A/M_REP_SELOP.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /C2A/REP_SELOPTS WHERE
(VIM_WHERETAB) .
    CLEAR /C2A/M_REP_SELOP .
/C2A/M_REP_SELOP-PROGNAME =
/C2A/REP_SELOPTS-PROGNAME .
/C2A/M_REP_SELOP-SEL_NAME =
/C2A/REP_SELOPTS-SEL_NAME .
/C2A/M_REP_SELOP-CDS_VIEW =
/C2A/REP_SELOPTS-CDS_VIEW .
/C2A/M_REP_SELOP-FIELDNAME =
/C2A/REP_SELOPTS-FIELDNAME .
<VIM_TOTAL_STRUC> = /C2A/M_REP_SELOP.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/C2A/M_REP_SELOP .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /C2A/M_REP_SELOP.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/C2A/M_REP_SELOP-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /C2A/REP_SELOPTS WHERE
  PROGNAME = /C2A/M_REP_SELOP-PROGNAME AND
  SEL_NAME = /C2A/M_REP_SELOP-SEL_NAME .
    IF SY-SUBRC = 0.
    DELETE /C2A/REP_SELOPTS .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /C2A/REP_SELOPTS WHERE
  PROGNAME = /C2A/M_REP_SELOP-PROGNAME AND
  SEL_NAME = /C2A/M_REP_SELOP-SEL_NAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /C2A/REP_SELOPTS.
    ENDIF.
/C2A/REP_SELOPTS-PROGNAME =
/C2A/M_REP_SELOP-PROGNAME .
/C2A/REP_SELOPTS-SEL_NAME =
/C2A/M_REP_SELOP-SEL_NAME .
/C2A/REP_SELOPTS-CDS_VIEW =
/C2A/M_REP_SELOP-CDS_VIEW .
/C2A/REP_SELOPTS-FIELDNAME =
/C2A/M_REP_SELOP-FIELDNAME .
    IF SY-SUBRC = 0.
    UPDATE /C2A/REP_SELOPTS ##WARN_OK.
    ELSE.
    INSERT /C2A/REP_SELOPTS .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/C2A/M_REP_SELOP-UPD_FLAG,
STATUS_/C2A/M_REP_SELOP-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/C2A/M_REP_SELOP.
  SELECT SINGLE * FROM /C2A/REP_SELOPTS WHERE
PROGNAME = /C2A/M_REP_SELOP-PROGNAME AND
SEL_NAME = /C2A/M_REP_SELOP-SEL_NAME .
/C2A/M_REP_SELOP-PROGNAME =
/C2A/REP_SELOPTS-PROGNAME .
/C2A/M_REP_SELOP-SEL_NAME =
/C2A/REP_SELOPTS-SEL_NAME .
/C2A/M_REP_SELOP-CDS_VIEW =
/C2A/REP_SELOPTS-CDS_VIEW .
/C2A/M_REP_SELOP-FIELDNAME =
/C2A/REP_SELOPTS-FIELDNAME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/C2A/M_REP_SELOP USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /C2A/M_REP_SELOP-PROGNAME TO
/C2A/REP_SELOPTS-PROGNAME .
MOVE /C2A/M_REP_SELOP-SEL_NAME TO
/C2A/REP_SELOPTS-SEL_NAME .
ENDFORM.
*---------------------------------------------------------------------*
