*---------------------------------------------------------------------*
*    view related data declarations
*---------------------------------------------------------------------*
*...processing: /C2A/M_EXT_HDR..................................*
TABLES: /C2A/M_EXT_HDR, */C2A/M_EXT_HDR. "view work areas
CONTROLS: TCTRL_/C2A/M_EXT_HDR
TYPE TABLEVIEW USING SCREEN '0001'.
DATA: BEGIN OF STATUS_/C2A/M_EXT_HDR. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/C2A/M_EXT_HDR.
* Table for entries selected to show on screen
DATA: BEGIN OF /C2A/M_EXT_HDR_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /C2A/M_EXT_HDR.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /C2A/M_EXT_HDR_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /C2A/M_EXT_HDR_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /C2A/M_EXT_HDR.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /C2A/M_EXT_HDR_TOTAL.

*...processing: /C2A/M_EXT_PAR..................................*
TABLES: /C2A/M_EXT_PAR, */C2A/M_EXT_PAR. "view work areas
CONTROLS: TCTRL_/C2A/M_EXT_PAR
TYPE TABLEVIEW USING SCREEN '0002'.
DATA: BEGIN OF STATUS_/C2A/M_EXT_PAR. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/C2A/M_EXT_PAR.
* Table for entries selected to show on screen
DATA: BEGIN OF /C2A/M_EXT_PAR_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /C2A/M_EXT_PAR.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /C2A/M_EXT_PAR_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /C2A/M_EXT_PAR_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /C2A/M_EXT_PAR.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /C2A/M_EXT_PAR_TOTAL.

*...processing: /C2A/M_IOC_CLIF.................................*
TABLES: /C2A/M_IOC_CLIF, */C2A/M_IOC_CLIF. "view work areas
CONTROLS: TCTRL_/C2A/M_IOC_CLIF
TYPE TABLEVIEW USING SCREEN '0005'.
DATA: BEGIN OF STATUS_/C2A/M_IOC_CLIF. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/C2A/M_IOC_CLIF.
* Table for entries selected to show on screen
DATA: BEGIN OF /C2A/M_IOC_CLIF_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /C2A/M_IOC_CLIF.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /C2A/M_IOC_CLIF_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /C2A/M_IOC_CLIF_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /C2A/M_IOC_CLIF.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /C2A/M_IOC_CLIF_TOTAL.

*...processing: /C2A/M_NAV......................................*
TABLES: /C2A/M_NAV, */C2A/M_NAV. "view work areas
CONTROLS: TCTRL_/C2A/M_NAV
TYPE TABLEVIEW USING SCREEN '0003'.
DATA: BEGIN OF STATUS_/C2A/M_NAV. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/C2A/M_NAV.
* Table for entries selected to show on screen
DATA: BEGIN OF /C2A/M_NAV_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /C2A/M_NAV.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /C2A/M_NAV_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /C2A/M_NAV_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /C2A/M_NAV.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /C2A/M_NAV_TOTAL.

*...processing: /C2A/M_NAV_EXIT.................................*
TABLES: /C2A/M_NAV_EXIT, */C2A/M_NAV_EXIT. "view work areas
CONTROLS: TCTRL_/C2A/M_NAV_EXIT
TYPE TABLEVIEW USING SCREEN '0004'.
DATA: BEGIN OF STATUS_/C2A/M_NAV_EXIT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/C2A/M_NAV_EXIT.
* Table for entries selected to show on screen
DATA: BEGIN OF /C2A/M_NAV_EXIT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /C2A/M_NAV_EXIT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /C2A/M_NAV_EXIT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /C2A/M_NAV_EXIT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /C2A/M_NAV_EXIT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /C2A/M_NAV_EXIT_TOTAL.

*...processing: /C2A/M_REPORT...................................*
TABLES: /C2A/M_REPORT, */C2A/M_REPORT. "view work areas
CONTROLS: TCTRL_/C2A/M_REPORT
TYPE TABLEVIEW USING SCREEN '0006'.
DATA: BEGIN OF STATUS_/C2A/M_REPORT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/C2A/M_REPORT.
* Table for entries selected to show on screen
DATA: BEGIN OF /C2A/M_REPORT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /C2A/M_REPORT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /C2A/M_REPORT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /C2A/M_REPORT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /C2A/M_REPORT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /C2A/M_REPORT_TOTAL.

*...processing: /C2A/M_REP_EXT..................................*
TABLES: /C2A/M_REP_EXT, */C2A/M_REP_EXT. "view work areas
CONTROLS: TCTRL_/C2A/M_REP_EXT
TYPE TABLEVIEW USING SCREEN '0009'.
DATA: BEGIN OF STATUS_/C2A/M_REP_EXT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/C2A/M_REP_EXT.
* Table for entries selected to show on screen
DATA: BEGIN OF /C2A/M_REP_EXT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /C2A/M_REP_EXT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /C2A/M_REP_EXT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /C2A/M_REP_EXT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /C2A/M_REP_EXT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /C2A/M_REP_EXT_TOTAL.

*...processing: /C2A/M_REP_PARAM................................*
TABLES: /C2A/M_REP_PARAM, */C2A/M_REP_PARAM. "view work areas
CONTROLS: TCTRL_/C2A/M_REP_PARAM
TYPE TABLEVIEW USING SCREEN '0007'.
DATA: BEGIN OF STATUS_/C2A/M_REP_PARAM. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/C2A/M_REP_PARAM.
* Table for entries selected to show on screen
DATA: BEGIN OF /C2A/M_REP_PARAM_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /C2A/M_REP_PARAM.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /C2A/M_REP_PARAM_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /C2A/M_REP_PARAM_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /C2A/M_REP_PARAM.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /C2A/M_REP_PARAM_TOTAL.

*...processing: /C2A/M_REP_SELOP................................*
TABLES: /C2A/M_REP_SELOP, */C2A/M_REP_SELOP. "view work areas
CONTROLS: TCTRL_/C2A/M_REP_SELOP
TYPE TABLEVIEW USING SCREEN '0008'.
DATA: BEGIN OF STATUS_/C2A/M_REP_SELOP. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/C2A/M_REP_SELOP.
* Table for entries selected to show on screen
DATA: BEGIN OF /C2A/M_REP_SELOP_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /C2A/M_REP_SELOP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /C2A/M_REP_SELOP_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /C2A/M_REP_SELOP_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /C2A/M_REP_SELOP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /C2A/M_REP_SELOP_TOTAL.

*.........table declarations:.................................*
TABLES: /C2A/EXT_HDR                   .
TABLES: /C2A/EXT_HDRT                  .
TABLES: /C2A/EXT_PAR                   .
TABLES: /C2A/EXT_PART                  .
TABLES: /C2A/IOC_CLIF                  .
TABLES: /C2A/NAVIGATION                .
TABLES: /C2A/NAV_EXIT                  .
TABLES: /C2A/REPORT                    .
TABLES: /C2A/REP_EXT                   .
TABLES: /C2A/REP_PARAMS                .
TABLES: /C2A/REP_SELOPTS               .
