CLASS zcl_cds_alv_version DEFINITION PUBLIC ABSTRACT FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    CONSTANTS version TYPE string VALUE '1.3.0' ##NO_TEXT.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_cds_alv_version IMPLEMENTATION.
ENDCLASS.
